openapi: 3.0.0
info:
  title: Book Review API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: A list of books
    post:
      summary: Add a new book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                published_year:
                  type: integer
      responses:
        '200':
          description: Book added

  /books/{id}:
    put:
      summary: Update a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                published_year:
                  type: integer
      responses:
        '200':
          description: Book updated

    delete:
      summary: Delete a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book deleted

  /books/{id}/reviews:
    post:
      summary: Add a review to a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reviewer:
                  type: string
                comment:
                  type: string
                rating:
                  type: integer
      responses:
        '200':
          description: Review added
