name: Keploy Test Workflow

on:
  push:
    branches:
      - main

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Keploy CLI
        run: |
          curl -sL https://dl.keploy.io/install.sh | bash
          echo "$HOME/.keploy" >> $GITHUB_PATH
          echo "$HOME/.keploy" >> $PATH
          ls $HOME/.keploy  # just to confirm it's installed
          chmod +x $HOME/.keploy/keploy

      - name: Run Keploy Tests
        run: |
          $HOME/.keploy/keploy test -c "python app.py" --delay 10
