- name: Install Keploy
  run: |
    curl -sL https://dl.keploy.io/install.sh | bash
    export PATH=$PATH:$HOME/.keploy
    keploy version

- name: Run Keploy Tests
  run: |
    keploy test -c "python app.py" --delay 10git add .github/workflows/keploy.yml